# Generated by Django 3.2.5 on 2021-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(max_length=50, verbose_name='خانه')),
                ('call', models.IntegerField(verbose_name='شماره تماس')),
                ('idea', models.TextField(verbose_name='نظرات')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
