# Generated by Django 3.2.5 on 2021-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('text', models.TextField()),
                ('rate', models.IntegerField(verbose_name='امتیاز')),
                ('time', models.IntegerField()),
                ('photo', models.ImageField(upload_to='foods/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BakingTime',
        ),
        migrations.RemoveField(
            model_name='basicmaterials',
            name='material',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='BasicMaterials',
        ),
        migrations.DeleteModel(
            name='NameFood',
        ),
    ]
