# Generated by Django 3.2.5 on 2021-08-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rate',
        ),
    ]
