# Generated by Django 3.2.5 on 2021-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('A', 'آش'), ('KH', 'خورشت'), ('AB', 'آبگوشت'), ('K', 'کوکو')], default='A', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
