# Generated by Django 3.2.5 on 2021-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('آش', 'آش'), ('خورشت', 'خورشت'), ('آبگوشت', 'آبگوشت'), ('کوکو', 'کوکو')], default='A', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
