# Generated by Django 3.2.5 on 2021-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_food_type_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='type_food',
        ),
        migrations.AlterField(
            model_name='food',
            name='text',
            field=models.TextField(verbose_name='مواد اولیه و توضیحات'),
        ),
    ]
